name: tests-payments

on:
  pull_request:
    paths:
      - 'microservices/ticketing/payments/**'  #It means run the below job only when certaing change is made in payments service.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing/payments && npm install
