name: tests-orders

on:
  pull_request:
    paths:
      - 'ticketing/orders/**' #It means run the below job only when certaing change is made in orders service.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing/orders && npm install
