name: tests-tickets

on:
  pull_request:
    paths:
      - '/ticketing/tickets/*'   #It means run the below job only when certaing change is made in tickets service.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing/tickets && npm install
