name: tests-auth

on: 
  pull_request
    paths:
      - 'auth/**'    #It means run the below job only when certaing change is made in auth service.
  
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing/auth && npm install
